# https://hub.docker.com/_/microsoft-dotnet

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
WORKDIR /src

# Copy project file and restore as distinct layers
COPY src/Services/BlueprintBase/BlueprintBase.csproj Services/BlueprintBase/
RUN dotnet restore "Services/BlueprintBase/BlueprintBase.csproj"

# Copy source code and publish app
COPY src/Services/ Services/
WORKDIR "/src/Services/BlueprintBase"

FROM build AS publish
RUN dotnet publish "BlueprintBase.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BlueprintBase.dll"]
